"""
Script Name: plot_ci.py

Author: Wen-Xuan Yue
ORCID: https://orcid.org/0009-0001-1298-6626
Affiliation: School of Life Sciences, Lanzhou University
Date: 2026-06-11

## Description

This script generates publication-style confidence interval plots
from the statistical results produced by KeyFeatureAnalysis.py.

Two figures are generated:

1. Organ Character Frequency Plot
2. Floral Character Frequency Plot

## Input

检索表关键词统计.xlsx

## Output

器官置信区间图.png
花特征置信区间图.png

## Visualization Elements

Point
Observed frequency estimated from the complete dataset.

Horizontal Error Bar
Bootstrap-derived 95% confidence interval (95% CI).

Letter Grouping
Statistical grouping based on pairwise bootstrap comparisons.

```
Categories sharing at least one letter indicate no obvious
difference.

Categories without a common letter indicate a relatively
clear difference.
```

## Data Source

The input data are generated by KeyFeatureAnalysis.py from
the angiosperm family-level identification keys of
*Key to the Vascular Plants of Inner Mongolia*.

## Notes

This script performs visualization only and does not conduct
statistical analyses.

All bootstrap estimates, confidence intervals, and significance
groupings are computed in KeyFeatureAnalysis.py and imported from
the Excel output file.

## Software Environment

Python 3.11

## Required Packages

pandas
numpy
matplotlib
openpyxl

"""

from pathlib import Path
import string
import pandas as pd
import matplotlib.pyplot as plt


XLSX_PATH = Path(__file__).parent / "检索表关键词统计.xlsx"

OUTPUT_ORGAN_PNG = Path(__file__).parent / "器官置信区间图.png"
OUTPUT_FLOWER_PNG = Path(__file__).parent / "花特征置信区间图.png"


# 尽量支持中文显示
plt.rcParams["font.sans-serif"] = [
    "Microsoft YaHei",
    "SimHei",
    "Arial Unicode MS"
]
plt.rcParams["axes.unicode_minus"] = False


def build_significance_letters(categories, pairwise_df):
    """
    根据两两比较结果生成显著性字母。

    规则：
        如果两类差异显著，则不能共用同一字母；
        如果两类差异不显著，则尽量共用同一字母。

    """

    significant_pairs = set()

    for _, row in pairwise_df.iterrows():
        a = row["A"]
        b = row["B"]
        sig = row["95%CI是否不跨0"]

        if sig == "是":
            significant_pairs.add(tuple(sorted([a, b])))

    letters = {}
    letter_groups = []

    for cat in categories:
        assigned = False

        for i, group in enumerate(letter_groups):
            can_join = True

            for old_cat in group:
                pair = tuple(sorted([cat, old_cat]))
                if pair in significant_pairs:
                    can_join = False
                    break

            if can_join:
                group.append(cat)
                letters[cat] = string.ascii_lowercase[i]
                assigned = True
                break

        if not assigned:
            letter_groups.append([cat])
            letters[cat] = string.ascii_lowercase[len(letter_groups) - 1]

    return letters


def plot_ci_chart(
    stat_sheet,
    pairwise_sheet,
    output_png,
    title,
    y_label
):
    df = pd.read_excel(XLSX_PATH, sheet_name=stat_sheet)
    pairwise = pd.read_excel(XLSX_PATH, sheet_name=pairwise_sheet)

    df = df.sort_values("原始比例", ascending=True).copy()

    categories = df["类别"].tolist()
    letters = build_significance_letters(categories, pairwise)

    x = df["原始比例"] * 100
    y = df["类别"]

    xerr_low = (df["原始比例"] - df["95%CI下限"]) * 100
    xerr_high = (df["95%CI上限"] - df["原始比例"]) * 100
    xerr = [xerr_low, xerr_high]

    fig_height = max(4.5, 0.45 * len(df) + 1.5)

    plt.figure(figsize=(7.5, fig_height))

    plt.errorbar(
        x,
        y,
        xerr=xerr,
        fmt="o",
        capsize=4,
        elinewidth=1.2,
        markersize=6
    )

    max_x = max(df["95%CI上限"] * 100)

    for _, row in df.iterrows():

        yi = row["类别"]

        ci_high = row["95%CI上限"] * 100

        plt.text(
            ci_high + max_x * 0.03,
            yi,
            letters[yi],
            va="center",
            fontsize=12,
            fontweight="bold"
        )

    plt.xlabel("出现比例（%）")
    plt.ylabel(y_label)
    plt.title(title)

    plt.xlim(0, max_x * 1.18)
    plt.tight_layout()

    plt.savefig(output_png, dpi=300)
    plt.close()

    print(f"已输出：{output_png}")


def main():
    plot_ci_chart(
        stat_sheet="器官Bootstrap统计",
        pairwise_sheet="器官两两比较",
        output_png=OUTPUT_ORGAN_PNG,
        title="不同器官特征在检索表中的使用频率",
        y_label="器官类别"
    )

    plot_ci_chart(
        stat_sheet="花特征Bootstrap统计",
        pairwise_sheet="花特征两两比较",
        output_png=OUTPUT_FLOWER_PNG,
        title="花部特征在检索表中的使用频率",
        y_label="花部特征类别"
    )


if __name__ == "__main__":
    main()
